# The following patch adds a singleton name validation to the CRD.
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: hierarchyconfigurations.hnc.x-k8s.io
spec:
  validation:
    openAPIV3Schema:
      properties:
        metadata:
          type: object
          properties:
            name:
              type: string
              pattern: '^hierarchy$'
