apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vc-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: vc-manager
    namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vc-manager
  namespace: kube-system
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vc-manager
  namespace: kube-system
  labels:
    app: vc-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vc-manager 
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: vc-manager
    spec:
      serviceAccountName: vc-manager
      containers:
      - command:
        - manager
        image: virtualcluster/manager-amd64 
        imagePullPolicy: Always
        name: vc-manager
